# Share sensitivities (per currency unit)
k_model: 0.02           # switching across models when representative model prices change
k_sku: 0.02             # switching within a model when SKU prices change
min_share_sku: 0.03     # minimum SKU share inside a model

# Constraints
max_price_move_pct: 0.15
price_tick: 5

# Optimizer
step: 5
max_iter: 300

# Baselines
baseline_days: 28
use_promos: true
